name: Maven build and package

on:
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: temurin

    - name: Maven build package
      run: |
        mvn build package
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: target
        path: target/ball-*.jar
